### ISSUE TITLE
Cant get past "open article in webbrowser"

### ISSUE THREAD

**Issue by nickblock** [shivam043/instantnews#18]
> Would you like to open an article in a web browser? Enter (y/n):
> y
> Traceback (most recent call last):
>   File "/home/nickb/.local/bin/instantnews", line 11, in <module>
>     sys.exit(parser())
>   File "/home/nickb/.local/lib/python2.7/site-packages/instantnews.py", line 171, in parser
>     show_news(args.news, BASE_URL)
>   File "/home/nickb/.local/lib/python2.7/site-packages/instantnews.py", line 122, in show_news
>     choice = (input()).lower()
>   File "<string>", line 1, in <module>
> NameError: name 'y' is not defined

Same happens if I enter a number.

**Comment by shivam043** [comment]
let me take a look @nickblock

**Comment by shivam043** [comment]
can you provide more information @nickblock ,because its working fine on my laptop

**Comment by jclement92** [comment]
I had this problem also. I got around it by typing the input as a string. I.E. `"y"` or `"n"`, with the quotes. Perhaps this can be reconfigured so that the quotes do not have to be entered?

**Comment by gabrielrondon** [comment]
Hi there. You should use `raw_input()` instead of `input()` when Python 2.7. 
Replace all the `input()` functions in this file /usr/local/lib/python2.7/site-packages/instantnews.py
This should solve the issue.
