### ISSUE TITLE
Unicode issues

### ISSUE THREAD

**Issue by dawilliams-gpsw** [shivam043/instantnews#19]
There seem to be some unicode issues on certain characters within the feeds. I'm seeing this error on almost every news site:

```
» in -n techcrunch
Traceback (most recent call last):
  File "/usr/local/bin/instantnews", line 11, in <module>
    sys.exit(parser())
  File "/Library/Python/2.7/site-packages/instantnews.py", line 171, in parser
    show_news(args.news, BASE_URL)
  File "/Library/Python/2.7/site-packages/instantnews.py", line 114, in show_news
    print('[{0}] {1}: {2}'.format(len(article_list), "Title", article['title']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 43: ordinal not in range(128)
```

```
» in -n cnbc
[0] Title: Trump says Michael Flynn's actions during transition were 'lawful' and 'there was nothing to hide'
Author: Javier E. David
Summary: President Donald Trump said he fired former national security advisor Michael Flynn for lying, but his actions were "lawful."
--------------------------------------------
[1] Title: Strategist Jim Paulsen says prepare for a stock market correction in 2018
Author: Trent Gillies
Summary: Jim Paulsen, Leuthold Group's chief investment strategist, says its time for investors to rebalance their 401(k)s since a market correction is coming soon.
--------------------------------------------
[2] Title: Even a $1 million retirement nest egg isn't enough anymore
Author: Jessica Dickler
Traceback (most recent call last):
  File "/usr/local/bin/instantnews", line 11, in <module>
    sys.exit(parser())
  File "/Library/Python/2.7/site-packages/instantnews.py", line 171, in parser
    show_news(args.news, BASE_URL)
  File "/Library/Python/2.7/site-packages/instantnews.py", line 116, in show_news
    print('{0}: {1}'.format("Summary", article['description']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 102: ordinal not in range(128)

```

```
» in -n bloomberg
[0] Title: Trump Says He's `Unbeatable' in 2020 on Tax Cuts, Stock Market
Author: Jennifer Jacobs
Traceback (most recent call last):
  File "/usr/local/bin/instantnews", line 11, in <module>
    sys.exit(parser())
  File "/Library/Python/2.7/site-packages/instantnews.py", line 171, in parser
    show_news(args.news, BASE_URL)
  File "/Library/Python/2.7/site-packages/instantnews.py", line 116, in show_news
    print('{0}: {1}'.format("Summary", article['description']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 197: ordinal not in range(128)
```

installed via pip

**Comment by shivam043** [comment]
Thanks @dawilliams-gpsw  for bringing in,i will look into it

**Comment by KZHAOUS** [comment]
The issue should be fixed by adding encode utf-8 in the description string.
line 116:
//print('{0}: {1}'.format("Summary", article['description'])
   print('{0}: {1}'.format("Summary", article['description'].encode("utf-8")))

**Comment by Benimautner** [comment]
If anyone else still this issue:
Firstly, download the project from source.
Then, add
 `reload(sys)
sys.setdefaultencoding('utf-8')
`
after the import line (  `import os, sys, argparse, webbrowser, requests` ) .
This should set the default encoding right, so it'll use utf-8 instead of ascii.
