### ISSUE TITLE
KeyError: 'articles'

### ISSUE THREAD

**Issue by Amarchuk** [shivam043/instantnews#20]
Hi! I install this package and be able to get codes/categories description, but when I try to run exact news-id, I get following error:

```bash
Traceback (most recent call last):
  File "c:\anaconda\envs\py353\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda\envs\py353\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\envs\py353\Scripts\instantnews.exe\__main__.py", line 9, in <module>
  File "c:\anaconda\envs\py353\lib\site-packages\instantnews.py", line 162, in parser
    show_news(args.news,BASE_URL)   
  File "c:\anaconda\envs\py353\lib\site-packages\instantnews.py", line 95, in show_news
    for i in t['articles']:
KeyError: 'articles'
```
I get API key, running on Windows7/Python3.5.3/cmd

**Comment by Amarchuk** [comment]
Ok, I figure it out: set wrong API key because put it into quotes. Sorry
